[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
gas_reports = [
    "LicenseProject"
]
optimizer = true
optimizer_runs = 200

# See more config options https://github.com/foundry-rs/foundry/tree/master/config